### ISSUE TITLE
Not discovering devices

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [0x7fffffff/Core-Bluetooth-Transfer-Demo#4]
Thanks for the example project. However it's not picking up any devices.

I ran it in my iPhone 5 (iOS 9.3.4). I had a laptop running Windows, an Android phone, an iPad Air 2 and my Mac all Bluetooth turned on. But none of those devices were discovered. `centralManagerDidUpdateState` method gets called and scanning starts but that's it. `didDiscoverPeripheral` method never gets called.

I repeated the process, this time ran it in the iPad Air 2 but same result.

Any idea why? Does the project still work properly from your end?

**Comment by mickmaccallum** [comment]
@Isuru-Nanayakkara It seems to still be functioning properly for me. If you're trying to detect arbitrary devices with this demo, that won't work, as the central manager is only looking for devices with certain characteristics (defined in Definitions.swift). And the peripheral manager is broadcasting using those characteristics. 

In short, all this demo was meant to do was allow you to discover one instead of it running in peripheral mode, from another instance running in central mode. I hope this helps.

**Comment by Isuru-Nanayakkara** [comment]
Oh I see. Thanks for the reply.
